### ISSUE TITLE
Move cli.py to demo level

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/tqdm_publisher#15]
I think it ought to be possible to move the `cli.py` file into the `src` package as long as you adjust the entrypoint and any other path  behaviors like imports, just to keep it nice and bundled together

**Comment by garrettmflynn** [comment]
Would the `demo` folder also then be moved there?

**Comment by CodyCBakerPhD** [comment]
Oh actually, that's right - never mind about `src`, but I'd put it in the `demo` folder since it's very specific to that

Maybe rename to `cli_demo.py` for clarity?

The actual location of the `demo` folder is good; reminiscent of a 'testing' folder which ought to live outside the main package to demonstration absolute imports
