### ISSUE TITLE
Actions coverage is zero-hit on src

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/tqdm_publisher#26]
OK so long story short; the CI was 'passing' since it was first added, but was actually failing the entire time. There was a specific flag I had to set to make it fail in the CI if the upload failed

Otherwise, it does not play well with the global upload token; it rather seems to be keyed specifically to an individual repo

Now that upload of report is working as expected, the actual actions themselves are showing zero hits in the src module: https://github.com/catalystneuro/tqdm_publisher/actions/runs/7705476623/job/20999463860

Was there anything special you had to do to get this to work locally?

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Nope nothing special. Running `pytest --cov=./src --cov-report xml:./codecov.xml` does it for me.

This command doesn't work for you locally?

**Comment by CodyCBakerPhD** [comment]
> This command doesn't work for you locally?

Haven't tried locally; main point is to get this working in the actions. Wonder if it's related to the puppeteer issues in actions too? Like, general async processes in that environment or something

**Comment by garrettmflynn** [comment]
Could it possibly have to do with the installation of `tqdm_publisher` which actually builds from the `pyproject.toml` instead of the test linking locally to `src`?
