### ISSUE TITLE
Adjust to use pyproject.toml builder

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/tqdm_publisher#8]
For a while now, the 'state-of-the-art' builder for Python packaging has been the `pyproject.toml` approach

@garrettmflynn I say we give it a try if you're up for it: https://packaging.python.org/en/latest/tutorials/packaging-projects/

(I'm also happy to handle this if you prefer)

HDMF-Zarr has used this recently: https://github.com/hdmf-dev/hdmf-zarr/blob/dev/pyproject.toml

Though I think we'd still stick to `setuptools` and not use `tox`

Ultimately we'd also have an adjusted [auto-release workflow](https://github.com/catalystneuro/neuroconv/blob/main/.github/workflows/auto-publish.yml) too

**Comment by garrettmflynn** [comment]
Sounds good. Was curious about this when I started configuring, I'll get a `pyproject.toml` going
