### ISSUE TITLE
Add numpy docstrings

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/tqdm_publisher#9]
Two methods of the class here are overrides

The `__init__.py` override dynamically passes all `args` and `kwargs` so that can (and should) inherit whatever docstring the parent has (no further action required on your part)

The `update` override does introduce an additional argument (`always_callback`), so something to think on here...
   - is this argument actually required? What is its effect? Is there any alternative way to handle this?
   - otherwise, will have to think on best way to handle this. The inherited docstring won't include the detail of this new parameter, and a manually defined docstring won't necessarily match up with a particular version of `tqdm`... This might be a case where dynamic docstring injection is actually appropriate

The other two new methods are missing docstrings and should really receive some that quickly and concisely describe how the methods should be called - `tqdm` appears to use NumPy docstring format, so be sure to follow that pattern

**Comment by garrettmflynn** [comment]
Got it, thanks for the feedback!

Looks like `always_callback` isn't really necessary. I'd found it on https://github.com/tqdm/tqdm/issues/845#issuecomment-671048817 where it looked like it was used—though I don't believe that this argument is ever actually passed.

**Comment by CodyCBakerPhD** [comment]
Oh, OK then - if that can be removed then the docstring for `update` can just be purely inherited, EZPZ
